name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: command
        run: echo ${{ env.SHOWCASE_ENV }}
      - run: npm install
      - run: npm test
      - run: docker build . -t "my-first-container:v0.0.3" 
      - run: docker tag my-first-container:v0.0.3 janvankant/dockerdemo:testversion     
      - run: docker push janvankant/dockerdemo:testversion
      
